image: ralfjung/opam-ci:opam2

stages:
  - build

variables:
  CPU_CORES: "10"
  OCAML: "ocaml-variants.4.14.0+options ocaml-option-flambda"
  # Avoid needlessly increasing our TCB with native_compute
  COQEXTRAFLAGS: "-native-compiler no"

.only_branches: &only_branches
  rules:
  - if: $CI_PROJECT_NAMESPACE != "iris"
    when: never
  - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "master"
  - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH =~ /^ci.*/

.only_mr: &only_mr
  rules:
  - if: $CI_PROJECT_NAMESPACE != "iris"
    when: never
  - if: $CI_PIPELINE_SOURCE == "merge_request_event"

.branches_and_mr: &branches_and_mr
  rules:
  - if: $CI_PROJECT_NAMESPACE != "iris"
    when: never
  - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "master"
  - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH =~ /^ci.*/
  - if: $CI_PIPELINE_SOURCE == "merge_request_event"

.branches_and_labeled_mr: &branches_and_labeled_mr
  rules:
  - if: $CI_PROJECT_NAMESPACE != "iris"
    when: never
  - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "master"
  - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH =~ /^ci.*/
  - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_LABELS =~ /.*CI-full.*/

.template: &template
  <<: *branches_and_labeled_mr
  stage: build
  interruptible: true
  tags:
  - fp
  script:
  - git clone https://gitlab.mpi-sws.org/iris/ci.git ci -b opam2
  - ci/buildjob
  cache:
    key: "$CI_JOB_NAME"
    paths:
    - _opam/

## Build jobs

# We are in Rocq's CI test suite, so better make sure we keep working with Rocq master.
build-rocq.dev:
  <<: *template
  variables:
    OCAML: "ocaml-base-compiler.4.14.0" # for faster rebuilds
    OPAM_PINS: "rocq-core version dev"

# The newest version runs with timing, outside MRs.
build-rocq.9.1.0:
  <<: *template
  <<: *only_branches
  variables:
    OPAM_PINS: "rocq-core version 9.1.0   rocq-stdlib version 9.0.0"
    DENY_WARNINGS: "1"
    MANGLE_NAMES: "1"
    OPAM_PKG: "1"
    DOC_DIR: "coqdoc@center.mpi-sws.org:iris"
    DOC_OPTS: "--external https://plv.mpi-sws.org/coqdoc/stdpp/ stdpp"
  tags:
  - fp-timing
  interruptible: false

# The newest version also runs in MRs, without timing.
build-rocq.9.1.0-mr:
  <<: *template
  <<: *only_mr
  variables:
    OPAM_PINS: "rocq-core version 9.1.0   rocq-stdlib version 9.0.0"
    DENY_WARNINGS: "1"
    MANGLE_NAMES: "1"

# Also ensure Dune works (broken on older Coq versions due to Stdlib split).
build-rocq.9.1.0-dune:
  <<: *template
  variables:
    OPAM_PINS: "rocq-core version 9.1.0   rocq-stdlib version 9.0.0"
    MAKE_TARGET: "dune"

# The oldest version runs in MRs, without name mangling.
build-rocq.9.0.1:
  <<: *template
  <<: *branches_and_mr
  variables:
    OPAM_PINS: "rocq-core version 9.0.1  rocq-stdlib version 9.0.0"
    DENY_WARNINGS: "1"

trigger-stdpp.dev:
  <<: *template
  variables:
    STDPP_REPO: "iris/stdpp"
    OPAM_PINS: "coq version $NIGHTLY_COQ   git+https://gitlab.mpi-sws.org/$STDPP_REPO#$STDPP_REV"
    CI_COQCHK: "1"
  rules:
  - if: $CI_PROJECT_NAMESPACE != "iris"
    when: never
  - if: $CI_PIPELINE_SOURCE =~ /^(trigger|api|schedule)$/
